server:
  port: 8761
spring:
  profiles: slaveA
  application:
      name: eureka-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://slave2:8762/eureka/
---
server:
  port: 8762
spring:
  profiles: slaveB
  application:
    name: eureka-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://slave1:8761/eureka/